### ISSUE TITLE
performance issue when use mysql

### ISSUE THREAD

**Issue by dimsua** [zensqlmonitor/influxdb-zabbix#10]
when we load data from mysql with default indexes like 
`KEY `history_uint_1` (`itemid`,`clock`)`
Performance was very poor, for example from table history_uint (300GB table-size) select for one month execute 3 days and i am interrupt them.

So its important to create indexes for clock column:
create index clock_idx on history_uint(clock);
create index clock_idx on history(clock);
create index clock_idx on trends(clock);
create index clock_idx on trends_uint(clock);

For trends_* table we can use pt-online-schema-change for online index create without lock, but for history_* table we can only use create index, because primary keys for this table doesnt exist (pt-online-schema-change can alter table when exist primary key)

**Comment by zensqlmonitor** [comment]
Thanks, I will add the indexes creation in the doc.
