### ISSUE TITLE
unexpected end of JSON input

### ISSUE THREAD

**Issue by dimsua** [zensqlmonitor/influxdb-zabbix#11]
After receive error "unexpected end of JSON" influxdb-zabbix stop parse table where got error.
2017/07/11 07:34:11 ESC[1;36m[T] --- Memory usage: Alloc = 1.1 MiB | TotalAlloc = 90 MiB | Sys = 4.8 MiB | NumGC = 3907ESC[0m
2017/07/11 07:34:11 ESC[1;32m[I] ----------- | history      | [2017-07-11 07:33:00 --> 2017-07-12 07:33:00[ESC[0m
2017/07/11 07:34:11 ESC[1;32m[I] <-- Extract | history      | 2909 rows in 197.634603msESC[0m
2017/07/11 07:34:11 ESC[1;32m[I] --> Load    | history      | 2909 rows in 41.746763msESC[0m
2017/07/11 07:34:11 ESC[1;32m[I] --- Waiting | history      | 15 sec ESC[0m
2017/07/11 07:34:26 ESC[1;36m[T] --- Memory usage: Alloc = 1.1 MiB | TotalAlloc = 90 MiB | Sys = 4.8 MiB | NumGC = 3908ESC[0m
2017/07/11 07:34:26 ESC[1;32m[I] ----------- | trends_uint  | [2017-07-11 06:00:00 --> 2017-08-10 06:00:00[ESC[0m
2017/07/11 07:34:26 ESC[1;32m[I] <-- Extract | trends_uint  | 0 rows in 2.856275msESC[0m
2017/07/11 07:34:26 ESC[1;32m[I] --> Load    | trends_uint  | No dataESC[0m
2017/07/11 07:34:26 ESC[1;32m[I] --- Waiting | trends_uint  | 15 sec ESC[0m
2017/07/11 07:34:28 ESC[1;36m[T] --- Memory usage: Alloc = 1.1 MiB | TotalAlloc = 90 MiB | Sys = 4.8 MiB | NumGC = 3908ESC[0m
2017/07/11 07:34:28 ESC[1;32m[I] ----------- | trends       | [2017-07-11 06:00:00 --> 2017-08-10 06:00:00[ESC[0m
2017/07/11 07:34:28 ESC[1;32m[I] <-- Extract | trends       | 0 rows in 1.110102msESC[0m
2017/07/11 07:34:28 ESC[1;32m[I] --> Load    | trends       | No dataESC[0m
2017/07/11 07:34:28 ESC[1;32m[I] --- Waiting | trends       | 15 sec ESC[0m
unexpected end of JSON input

2017/07/11 09:30:50 ESC[1;36m[T] --- Memory usage: Alloc = 1.7 MiB | TotalAlloc = 123 MiB | Sys = 4.8 MiB | NumGC = 3978ESC[0m
2017/07/11 09:30:50 ESC[1;32m[I] ----------- | trends       | [2017-07-11 08:00:00 --> 2017-08-10 08:00:00[ESC[0m
2017/07/11 09:30:50 ESC[1;32m[I] <-- Extract | trends       | 0 rows in 1.15126msESC[0m
2017/07/11 09:30:50 ESC[1;32m[I] --> Load    | trends       | No dataESC[0m
2017/07/11 09:30:50 ESC[1;32m[I] --- Waiting | trends       | 15 sec ESC[0m
unexpected end of JSON input

and then influxdb-zabbix stop parse history and trends table 
Log here: https://scr.pics/output_4.log

**Comment by zensqlmonitor** [comment]
Please send me the content of the registry / json file.

**Comment by dimsua** [comment]
influxdb-zabbix.json ?
[root@zabbix influxdb-zabbix]# cat influxdb-zabbix.json
[
    {
        "Table": "history",
        "Startdate": "2017-07-11T07:34:09+03:00"
    },
    {
        "Table": "history_uint",
        "Startdate": "2017-04-27T11:00:00Z"
    },
    {
        "Table": "trends",
        "Startdate": "2017-07-11T08:00:00+03:00"
    },
    {
        "Table": "trends_uint",
        "Startdate": "2017-07-11T11:00:00+03:00"
    }
][root@zabbix influxdb-zabbix]#

**Comment by dimsua** [comment]
looks like app parse json file when write to it (json invalid in this time) and recieve error
because after app restart - all work fine

**Comment by zensqlmonitor** [comment]
ok, nice
