### ISSUE TITLE
Some grants are missing from the doc

### ISSUE THREAD

**Issue by frakev** [zensqlmonitor/influxdb-zabbix#14]
Hello,

It lacking some GRANTS on MySQL tables from the documentation:

GRANT SELECT ON zabbix.items_applications TO influxdb_zabbix@localhost;
GRANT SELECT ON zabbix.applications TO influxdb_zabbix@localhost;
GRANT SELECT ON zabbix.items TO influxdb_zabbix@localhost;
GRANT SELECT ON zabbix.hosts TO influxdb_zabbix@localhost;
GRANT SELECT ON zabbix.hosts_groups TO influxdb_zabbix@localhost;
GRANT SELECT ON zabbix.groups TO influxdb_zabbix@localhost;

Thx

**Comment by ghost** [comment]
+1
we have experimented same issue. 
Can you confirm the need of the additional grants?

thank you

**Comment by zensqlmonitor** [comment]
Tks, fixed
