### ISSUE TITLE
Error in start

### ISSUE THREAD

**Issue by stepanovandrey89** [zensqlmonitor/influxdb-zabbix#15]
root@localhost:/opt/go/bin# go run influxdb-zabbix.go &
[5] 20535
root@localhost:/opt/go/bin# 2018/08/29 12:35:04 [T] Log Mode: Console(Trace)
2018/08/29 12:35:04 [T] --- Active tables:
2018/08/29 12:35:04 [T] ----------- | history_uint | Each 15 sec | 30 days per batch | Output by 50000
2018/08/29 12:35:04 [T] ----------- | trends | Each 15 sec | 30 days per batch | Output by 50000
2018/08/29 12:35:04 [T] ----------- | trends_uint | Each 15 sec | 30 days per batch | Output by 50000
2018/08/29 12:35:04 [T] ----------- | history | Each 15 sec | 30 days per batch | Output by 50000
2018/08/29 12:35:04 [I] --- Start polling
2018/08/29 12:35:04 [T] --- Provider: mysql
2018/08/29 12:35:04 [...db-zabbix/log/log.go:299 Error()] [E] Error while executing script: Error 1146: Table 'zabbix.groups' doesn't exist
2018/08/29 12:35:04 [...db-zabbix/log/log.go:299 Error()] [E] Error while executing script: Error 1146: Table 'zabbix.groups' doesn't exist

**Comment by guillerial** [comment]
@stepanovandrey89  I have the same problem. Did you find any solution?
![image](https://user-images.githubusercontent.com/12005750/47914064-81e0ea00-de9e-11e8-860c-03a5870dc1bb.png)

**Comment by stepanovandrey89** [comment]
Check this table in 3x version.
4x version dont consist this table. I am duplicate(create) table.

пт, 2 нояб. 2018 г. в 14:54, Guillermo Rial Salgueiro <
notifications@github.com>:

**Comment by guillerial** [comment]
groups table is now hstgrp table. I changed this on mysql.go and it works. Zabbix 4.0

Check this:
https://github.com/guillerial/influxdb-zabbix/commit/b5a176b39abb201fee505d2e644c5447f8020105

**Comment by zensqlmonitor** [comment]
ok fixed
