### ISSUE TITLE
hstgrp not found

### ISSUE THREAD

**Issue by ajurquhart** [zensqlmonitor/influxdb-zabbix#20]
Zabbix running with MySQL. Zabbix version 3.4.7.

When I attempt to launch influx-zabbix I get an error: [...db-zabbix/log/log.go:299 Error()] [E] Error while executing script: Error 1146: Table 'zabbix.hstgrp' doesn't exist

The error is accurate, as that Table does not exist, and never has.
How do I omit the query that looks for hstgrp Table?

**Comment by i-ky** [comment]
You can either upgrade your Zabbix setup (3.4 is not supported for quite some time) or use older version of this project prior to #16.
