### ISSUE TITLE
Some values are not imported

### ISSUE THREAD

**Issue by cayetano** [zensqlmonitor/influxdb-zabbix#8]
First: Thanks it is a good tool for graphics generation.

I'm a problem some data, like "Memory Available" from Linux Template are not imported.

select * from  /disk/ where time > now() - 10m group by host_name
return data

and 
select * from  /Free mem/ where time > now() - 10m group by host_name
no return data

I have an item : "Free memory" in > 1000 Host, an 30s interval capture in the same template than disk items.

What am I doing wrong?

.log say (fraction )
2017/06/14 21:34:36 [I] --> Load    | history             | 1642 rows | took 44.216453ms
2017/06/14 21:34:36 [I] --- Waiting | history             | 15 sec
2017/06/14 21:34:41 [I] ----------- | trends_uint         | [2017-06-14 20:00 --> 2017-06-19 00:00[
2017/06/14 21:34:41 [I] <-- Extract | trends_uint         | 0 rows | took 2m14.218816043s
2017/06/14 21:34:41 [I] --> Load    | trends_uint         | No data
2017/06/14 21:34:41 [I] --- Waiting | trends_uint         | 15 sec
2017/06/14 21:34:41 [I] ----------- | trends              | [2017-06-14 20:00 --> 2017-06-19 00:00[
2017/06/14 21:34:41 [I] <-- Extract | trends              | 0 rows | took 2m14.216457812s
2017/06/14 21:34:41 [I] --> Load    | trends              | No data
2017/06/14 21:34:41 [I] --- Waiting | trends              | 15 sec
2017/06/14 21:34:52 [I] ----------- | history             | [2017-06-14 21:34 --> 2017-06-19 01:34[
2017/06/14 21:34:52 [I] <-- Extract | history             | 1537 rows | took 525.689065ms
2017/06/14 21:34:52 [I] --> Load    | history             | 1537 rows | took 74.314333ms
2017/06/14 21:34:52 [I] --- Waiting | history             | 15 sec
2017/06/14 21:35:08 [I] ----------- | history             | [2017-06-14 21:34 --> 2017-06-19 01:34[
2017/06/14 21:35:08 [I] <-- Extract | history             | 1936 rows | took 828.63425ms
2017/06/14 21:35:08 [I] --> Load    | history             | 1936 rows | took 58.445102ms
2017/06/14 21:35:08 [I] --- Waiting | history             | 15 sec
2017/06/14 21:35:24 [I] ----------- | history             | [2017-06-14 21:35 --> 2017-06-19 01:35[
2017/06/14 21:35:24 [I] <-- Extract | history             | 1862 rows | took 1.311703982s
2017/06/14 21:35:24 [I] --> Load    | history             | 1862 rows | took 56.305334ms
2017/06/14 21:35:24 [I] --- Waiting | history             | 15 sec
2017/06/14 21:35:40 [I] ----------- | history             | [2017-06-14 21:35 --> 2017-06-19 01:35[
2017/06/14 21:35:40 [I] <-- Extract | history             | 1892 rows | took 391.909308ms
2017/06/14 21:35:40 [I] --> Load    | history             | 1892 rows | took 76.531357ms
2017/06/14 21:35:40 [I] --- Waiting | history             | 15 sec
2017/06/14 21:35:56 [I] ----------- | history             | [2017-06-14 21:35 --> 2017-06-19 01:35[
2017/06/14 21:35:56 [I] <-- Extract | history             | 1383 rows | took 1.067275888s
2017/06/14 21:35:56 [I] --> Load    | history             | 1383 rows | took 53.247276ms
2017/06/14 21:35:56 [I] --- Waiting | history             | 15 sec
2017/06/14 21:36:12 [I] ----------- | history             | [2017-06-14 21:35 --> 2017-06-19 01:35[
2017/06/14 21:36:12 [I] <-- Extract | history             | 1885 rows | took 1.133679853s
2017/06/14 21:36:12 [I] --> Load    | history             | 1885 rows | took 57.551265ms
2017/06/14 21:36:12 [I] --- Waiting | history             | 15 sec

Regards,
Cayetano

p.s. sorry, y have a poor english

**Comment by zensqlmonitor** [comment]
Hi @cayetano , it looks like you have not enabled the table history_uint in the config file.

**Comment by cayetano** [comment]
Good Morning

My .conf file, partially, is :
[tables]
  [tables.history]
  name="history"
  active=true
  startdate="2017-06-10T00:00:00"
  hoursperbatch=100
  outputrowsperbatch=50000
  interval=15

  [tables.history_uint]
  name="history_uint"
  active=true
  startdate="2017-06-10T00:00:00"
  hoursperbatch=100
  outputrowsperbatch=50000
  interval=15

  [tables.trends]
  name="trends"
  active=true
  startdate="2017-06-10T00:00:00"
  hoursperbatch=100
  outputrowsperbatch=50000
  interval=15

  [tables.trends_uint]
  name="trends_uint"
  active=true
  startdate="2017-06-10T00:00:00"
  hoursperbatch=100
  outputrowsperbatch=50000
  interval=15



An .json file is

[
    {
        "Table": "trends_uint",
        "Startdate": "2017-06-15T11:00:00+02:00"
    },
    {
        "Table": "history",
        "Startdate": "2017-06-15T12:43:10+02:00"
    },
    {
        "Table": "history_uint",
        "Startdate": "2017-06-10T00:00:00"
    },
    {
        "Table": "trends",
        "Startdate": "2017-06-15T11:00:00+02:00"
    }
]


In Mysql database history_uint have some millions of records

Regards

Cayetano

2017-06-15 6:40 GMT+02:00 zensqlmonitor <notifications@github.com>:

**Comment by zensqlmonitor** [comment]
Regarding the registry file (json), you haven't got the result of the table as shown there:
 {
        "Table": "history_uint",
        "Startdate": "2017-06-10T00:00:00"
    },

If Startdate = startdate in config file, the first dataset is not yet resulted.

Have u tried to rebuild the default indexes on the tables ?
You can also try to disable all tables excepted this one and wait for the result ?

**Comment by cayetano** [comment]
I'm detect problem

The sql connection close the connection prior to receive data.
If the database is big, the sql process take more time.

Regards.
Cayetano

2017-06-19 21:55 GMT+02:00 zensqlmonitor <notifications@github.com>:
