### ISSUE TITLE
"error":"partial write: unable to parse

### ISSUE THREAD

**Issue by dimsua** [zensqlmonitor/influxdb-zabbix#9]
Hello
Try to load data from zabbix to influxdb:
2017/07/05 12:35:55 ESC[1;36m[T] Log Mode: Console(Trace)ESC[0m
2017/07/05 12:35:55 ESC[1;36m[T] --- Active tables:ESC[0m
2017/07/05 12:35:55 ESC[1;36m[T] ----------- | history      | Each 15 sec | 30 days per batch | Output by 50000ESC[0m
2017/07/05 12:35:55 ESC[1;36m[T] ----------- | history_uint | Each 15 sec | 30 days per batch | Output by 50000ESC[0m
2017/07/05 12:35:55 ESC[1;36m[T] ----------- | trends       | Each 15 sec | 30 days per batch | Output by 50000ESC[0m
2017/07/05 12:35:55 ESC[1;36m[T] ----------- | trends_uint  | Each 15 sec | 30 days per batch | Output by 50000ESC[0m
2017/07/05 12:35:55 ESC[1;32m[I] --- Start pollingESC[0m
2017/07/05 12:35:55 ESC[1;36m[T] --- Provider: mysqlESC[0m
2017/07/05 13:04:55 ESC[1;31m[...db-zabbix/log/log.go:299 Error()] [E] Error while loading data for trends. {"error":"partial write: unable to parse 'a10.kw,host_name=A10\\ datapro,group_name=PDU\\ Units,applications=No application value_min=5.5220,value_avg=5.6861,value_max=5.9620 1483232400000': invalid field format\n

Full log: https://scr.pics/output.log

**Comment by dimsua** [comment]
zabbix: 3.0.9
mysql: 5.7
os: centos 7

**Comment by zensqlmonitor** [comment]
I just commited a fix. Could you please have a try ?

**Comment by dimsua** [comment]
Looks like all work fine now.
Thank you.
